### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by mulysatest** [jadr2ddude/ds4#1]
I have connected dualshock4 with osx and run your code, but nothing happen just blank screen. Nothing print out even I have press all button. 

While in another gobot joystick example "scanner" it print out all pressed key properly.

**Comment by jadr2ddude** [comment]
Hi. This is Linux-specific. This will not work on OSX.

**Comment by mulysatest** [comment]
but your code based on joystick lib on gobot, it should work on cross platform right?

**Comment by mulysatest** [comment]
can you try if this code work for you https://www.drone-engineer.com/articles/766
